version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar pip y dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Instalar flake8
          command: pip install flake8
      - run:
          name: Ejecutar Linting con flake8
          command: flake8 .
  test:
    docker:
      - image: cimg/python:3.9
        environment:
          ELASTICSEARCH_HOST: "elasticsearch"
      - image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
        name: elasticsearch
        environment:
          discovery.type: "single-node"
          xpack.security.enabled: "false"
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Esperar a que Elasticsearch se inicie
          command: |
            # Espera hasta que Elasticsearch responda en el puerto 9200
            until curl --fail http://elasticsearch:9200; do
              echo "Esperando a que Elasticsearch se inicie..."
              sleep 5
            done
      - run:
          name: Ejecutar tests con pytest
          command: pytest
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint:
          filters:
            branches:
              only: dev
      - test:
          requires:
            - lint
          filters:
            branches:
              only: dev
