version: 2.1

orbs:
  ggshield: gitguardian/ggshield@1.1.0

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo

jobs:
  security:
    executor: python-executor
    steps:
      - checkout
      - ggshield/scan:
          type: repo
          path: .

  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar pip y dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Instalar flake8
          command: pip install flake8
      - run:
          name: Ejecutar linting con flake8
          command: flake8 .

  test:
    docker:
      - image: cimg/python:3.9
        environment:
          ELASTICSEARCH_HOST: "elasticsearch"
      - image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
        name: elasticsearch
        environment:
          discovery.type: "single-node"
          xpack.security.enabled: "false"
    steps:
      - checkout
      - run:
          name: Instalar dependencias y coverage
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install coverage
      - run:
          name: Esperar a que Elasticsearch se inicie
          command: |
            until curl --fail http://elasticsearch:9200; do
              echo "Esperando a que Elasticsearch se inicie..."
              sleep 5
            done
      - run:
          name: Ejecutar tests y generar cobertura
          command: |
            coverage run -m pytest
            coverage report --fail-under=80
      - run:
          name: Generar reporte XML de cobertura
          command: coverage xml
      - store_artifacts:
          path: coverage.xml
          destination: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - security:
          filters:
            branches:
              only: dev
      - lint:
          requires:
            - security
          filters:
            branches:
              only: dev
      - test:
          requires:
            - lint
          filters:
            branches:
              only: dev
