name: Deploy Pipeline

on:
    push:
      branches:
        - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('app/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Upgrade pip
        run: pip3 install --upgrade pip

  ggshield_scan:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install ggshield
        run: pip install ggshield

      - name: Scan code for secrets
        run: ggshield scan repo .

  linting_action:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore pip cache
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: pip-${{ hashFiles('requirements.txt') }}
            restore-keys: |
              pip-

      - name: Set up virtualenv and install dependencies
        run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - name: Run Pylint
        run: |
          source venv/bin/activate
          pylint --rcfile=app/.pylintrc app/app.py

  test_coverage_action:
    runs-on: ubuntu-latest
    needs: linting_action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore pip cache
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: pip-${{ hashFiles('requirements.txt') }}
            restore-keys: |
              pip-

      - name: Set up virtualenv and install dependencies
        run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt    

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v --tb=short

      - name: Run coverage
        run: |
          source venv/bin/activate
          pytest --cov=app --cov-report=xml app/test_app.py

  sonarqube_analysis:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: test_coverage_action
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  semantic_release:
    runs-on: ubuntu-latest
    needs: test_coverage_action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies for semantic-release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator conventional-changelog-conventionalcommits@6

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  build_push_image:
    runs-on: ubuntu-latest
    needs: semantic_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  notify_slack:
    runs-on: ubuntu-latest
    needs: build_push_image
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Get workflow status
        id: get_status
        run: echo "status=${{ needs.build_push_image.result }}" >> $GITHUB_OUTPUT

      - name: Extract changelog from latest release
        run: |
          gh release view --json body -q ".body" > changelog.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
        run: |
          if [ "${{ needs.build_push_image.result }}" == "success" ]; then
            status_emoji="✅"
          else
            status_emoji="❌"
          fi

          changelog=$(sed 's/^\* /• /' changelog.txt | sed 's/"/\\"/g')

          payload="{
            \"text\": \"$status_emoji *[Deploy Pipeline]*\\n*Repository:* ${{ github.repository }}\\n*Branch:* ${{ github.ref_name }}\\n*Status:* ${{ needs.build_push_image.result }}\\n\\n*Changelog:*\\n$changelog\"
          }"

          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"